import React, { createContext, useState ,useContext} from 'react'

 const contextApi = createContext()

 const gamingProducts = [
  {
    id: 1,
    name: "RGB Mechanical Keyboard",
    price: 89,
    category: "Keyboard",
    rating: 4.6,
    img: "/photo/download2.avif",
    description: "Blue switch + RGB spectrum keys",
  },
  {
    id: 2,
    name: "Wireless Gaming Mouse",
    price: 49,
    category: "Mouse",
    rating: 4.4,
    img: "/photo/mouse1.avif",
    description: "Adjustable DPI up to 16000",
  },
  {
    id: 3,
    name: "Gaming Headset 7.1",
    price: 69,
    category: "Headset",
    rating: 4.5,
    img: "/photo/headphone1.avif",
    description: "7.1 surround sound ",
  },
  {
    id: 4,
    name: "Gaming Monitor 165Hz",
    price: 199,
    category: "Monitor",
    rating: 4.7,
    img: "/photo/moniter1.jpg",
    description: "24-inch FHD 165Hz IPS display",
  },
  {
    id: 5,
    name: "RGB Gaming Chair",
    price: 229,
    category: "Chair",
    rating: 4.3,
    img: "/photo/chair1.avif",
    description: "Ergonomic build + RGB edges",
  },
  {
    id: 6,
    name: "PS5 Console",
    price: 499,
    category: "Console",
    rating: 4.9,
    img: "/photo/console1.avif",
    description: "4K gaming + next-gen SSD loading",
  },
  {
    id: 7,
    name: "Xbox Series X",
    price: 499,
    category: "Console",
    rating: 4.8,
    img: "/photo/console1.avif",
    description: "True 4K 120FPS gaming console",
  },
  {
    id: 8,
    name: "Nintendo Switch",
    price: 299,
    category: "Console",
    rating: 4.7,
    img: "/photo/Nintendo.jpg",
    description: "Portable hybrid gaming console",
  },
  {
    id: 9,
    name: "Gaming Desk RGB",
    price: 159,
    category: "Desk",
    rating: 4.5,
    img: "/photo/Desk.avif",
    description: "Carbon fiber top + RGB edges",
  },
  {
    id: 10,
    name: "4K Capture Card",
    price: 129,
    category: "Streaming",
    rating: 4.6,
    img: "/photo/CaptureCard.jpg",
    description: "4K30 HDR capture for streaming",
  },

  // More products
  {
    id: 11,
    name: "VR Gaming Headset",
    price: 349,
    category: "VR",
    rating: 4.4,
    img: "/photo/headphone2.avif",
    description: "Immersive VR experience",
  },
  {
    id: 12,
    name: "RGB Mouse Pad XL",
    price: 29,
    category: "Accessories",
    rating: 4.7,
    img: "/photo/mouse1.avif",
    description: "Anti-slip + RGB strip lighting",
  },
  {
    id: 13,
    name: "Gaming GPU RTX 4060",
    price: 399,
    category: "GPU",
    rating: 4.8,
    img: "/photo/GPU.jpg",
    description: "8GB GDDR6 + DLSS 3",
  },
  {
    id: 14,
    name: "Gaming GPU RTX 4070",
    price: 599,
    category: "GPU",
    rating: 4.9,
    img: "/photo/GPU.jpg",
    description: "12GB GDDR6X + Ray tracing",
  },
  {
    id: 15,
    name: "AMD Ryzen 7 5800X",
    price: 289,
    category: "CPU",
    rating: 4.9,
    img: "/photo/chip.jpg",
    description: "8 core gaming CPU",
  },
  {
    id: 16,
    name: "Intel i7 12700KF",
    price: 320,
    category: "CPU",
    rating: 4.8,
    img: "/photo/chip.jpg",
    description: "High-end gaming processor",
  },
  {
    id: 17,
    name: "Gaming RAM 16GB RGB",
    price: 79,
    category: "RAM",
    rating: 4.7,
    img: "/photo/ram.jpg",
    description: "DDR4 3600MHz RGB kit",
  },
  {
    id: 18,
    name: "Gaming RAM 32GB DDR5",
    price: 159,
    category: "RAM",
    rating: 4.8,
    img: "/photo/ram.jpg",
    description: "DDR5 5600MHz performance RAM",
  },
  {
    id: 19,
    name: "500GB NVMe SSD",
    price: 59,
    category: "Storage",
    rating: 4.6,
    img: "/photo/ssd.jpg",
    description: "3500MB/s read speed",
  },
  {
    id: 20,
    name: "1TB NVMe SSD Gen4",
    price: 129,
    category: "Storage",
    rating: 4.8,
    img: "/photo/ssd.jpg",
    description: "7000MB/s read speed",
  },

  // 21–30
  {
    id: 21,
    name: "Mechanical Switch Set",
    price: 25,
    category: "Keyboard",
    rating: 4.3,
    img: "/photo/switch.jpg",
    description: "Pack of 35 hot-swap switches",
  },
  {
    id: 22,
    name: "Gaming Controller RGB",
    price: 49,
    category: "Controller",
    rating: 4.5,
    img: "/photo/download3.avif",
    description: "PC + console compatible",
  },
  {
    id: 23,
    name: "Pro Microphone",
    price: 89,
    category: "Streaming",
    rating: 4.7,
    img: "/photo/headphone1.avif",
    description: "Studio quality + noise filter",
  },
  {
    id: 24,
    name: "Gaming Webcam 1080p",
    price: 59,
    category: "Streaming",
    rating: 4.4,
    img: "/photo/webcam.jpg",
    description: "Full HD with autofocus",
  },
  {
    id: 25,
    name: "RGB Case Fan 120mm",
    price: 19,
    category: "Cooling",
    rating: 4.6,
    img: "/photo/Fan.jpg",
    description: "Ultra-quiet + RGB",
  },
  {
    id: 26,
    name: "AIO Liquid Cooler",
    price: 119,
    category: "Cooling",
    rating: 4.8,
    img: "/photo/cooling.webp",
    description: "240mm ARGB liquid cooler",
  },
  {
    id: 27,
    name: "Gaming PC Case RGB",
    price: 99,
    category: "Case",
    rating: 4.6,
    img: "/photo/case.webp",
    description: "Glass side panel + RGB fans",
  },
  {
    id: 28,
    name: "Gaming Laptop 144Hz",
    price: 899,
    category: "Laptop",
    rating: 4.7,
    img: "",
    description: "GTX 1650 + 144Hz screen",
  },
  {
    id: 29,
    name: "4K Gaming Laptop",
    price: 1499,
    category: "Laptop",
    rating: 4.9,
    img: "https://i.ibb.co/yFJv5F4/l2.jpg",
    description: "RTX 3070 + 4K panel",
  },
  {
    id: 30,
    name: "Portable Keyboard",
    price: 39,
    category: "Keyboard",
    rating: 4.4,
    img: "/photo/download2.avif",
    description: "60% compact mechanical keyboard",
  },

  // 31–40
  {
    id: 31,
    name: "1080p Portable Projector",
    price: 159,
    category: "Projector",
    rating: 4.4,
    img: "https://i.ibb.co/P1s1pYQ/proj1.jpg",
    description: "Gaming + home theater projector",
  },
  {
    id: 32,
    name: "Racing Wheel Set",
    price: 299,
    category: "Controller",
    rating: 4.7,
    img: "https://i.ibb.co/C5Nx9S1/wheel1.jpg",
    description: "Force feedback racing wheel",
  },
  {
    id: 33,
    name: "RGB Lightbar",
    price: 35,
    category: "Accessories",
    rating: 4.5,
    img: "https://i.ibb.co/MswysdF/light1.jpg",
    description: "Syncs with gaming audio",
  },
  {
    id: 34,
    name: "Gaming Glasses",
    price: 25,
    category: "Accessories",
    rating: 4.3,
    img: "https://i.ibb.co/hK2W8j1/gls1.jpg",
    description: "Anti-blue light protection",
  },
  {
    id: 35,
    name: "360 Microphone Arm",
    price: 29,
    category: "Streaming",
    rating: 4.6,
    img: "https://i.ibb.co/n1zKG3s/arm1.jpg",
    description: "Fully flexible mic stand",
  },
  {
    id: 36,
    name: "Gaming USB Hub RGB",
    price: 22,
    category: "Accessories",
    rating: 4.4,
    img: "https://i.ibb.co/YTW4VW1/hub1.jpg",
    description: "7-port USB hub with RGB",
  },
  {
    id: 37,
    name: "Gamepad Charging Dock",
    price: 19,
    category: "Accessories",
    rating: 4.5,
    img: "https://i.ibb.co/ThFw16t/dock1.jpg",
    description: "Fast charging dual dock",
  },
  {
    id: 38,
    name: "RGB GPU Support Bracket",
    price: 18,
    category: "Accessories",
    rating: 4.3,
    img: "/photo/GPU.jpg",
    description: "Prevents GPU sag",
  },
  {
    id: 39,
    name: "Game Storage Tower",
    price: 45,
    category: "Accessories",
    rating: 4.4,
    img: "/photo/ssd.jpg",
    description: "Holds 36 game discs",
  },
  {
    id: 40,
    name: "RGB Soundbar",
    price: 59,
    category: "Audio",
    rating: 4.6,
    img: "https://i.ibb.co/WzmGfkM/soundbar1.jpg",
    description: "RGB + deep bass",
  },


];


const ProductList = ({children}) => {
    const [data,setData] = useState([])

   return (
   <contextApi.Provider value={{data,setData,gamingProducts}}>

    {children}
   </contextApi.Provider>
  )
}

export default ProductList




export function Helper(){

    return useContext(contextApi)
}
